In [15]:
import pandas as pd

reviews = pd.read_csv("../data/raw/GooglePlay_App_Data.csv")

In [16]:
import os

os.getcwd()

'/Users/krrishmujoo/Desktop/sentiment analyser project/notebooks'

In [17]:
reviews.head()

,review_id,user_name,review_title,review_description,rating,thumbs_up,review_date,developer_response,developer_response_date,appVersion,laguage_code,country_code
0,81942ead-9d65-4b1a-8aa2-6e21ad5cf5e7,Vernalee Fortin,NaN,"Still loving it!, the best!",5,0,9/3/2024 0:23,NaN,NaN,23.12.04000,en,us
1,c08cf1e7-45e4-43a3-b86f-51f7809b80a3,Toki Doki,NaN,Convenient one stop app for all your passwords...,5,0,8/19/2024 3:32,NaN,NaN,23.12.04000,en,us
2,c8937763-e1b4-43b1-9e48-cde58be80111,CJ Cross,NaN,Tried several password managers until I came a...,5,0,7/30/2024 8:07,NaN,NaN,23.12.04000,en,us
3,762baf4b-9109-4b4b-a42f-2291b0486faf,Trevor Lewis,NaN,Ok thank you,5,0,6/11/2024 17:20,NaN,NaN,NaN,en,us
4,275a2d36-6d77-44ae-9d7b-8be6ad614e3f,K K,NaN,switched phones and none of my passwords came ...,1,0,5/19/2024 19:20,You have to do a backup on Google Drive / Drop...,5/21/2024 23:50,23.12.04000,en,us

In [18]:
reviews.shape

(161, 12)

In [19]:
reviews.columns

Index(['review_id', 'user_name', 'review_title', 'review_description',
       'rating', 'thumbs_up', 'review_date', 'developer_response',
       'developer_response_date', 'appVersion', 'laguage_code',
       'country_code'],
      dtype='object')

In [21]:
reviews.dtypes

review_id                   object
user_name                   object
review_title               float64
review_description          object
rating                       int64
thumbs_up                    int64
review_date                 object
developer_response          object
developer_response_date     object
appVersion                  object
laguage_code                object
country_code                object
dtype: object

In [23]:
reviews.isnull().sum()

review_id                    0
user_name                    0
review_title               161
review_description           0
rating                       0
thumbs_up                    0
review_date                  0
developer_response         111
developer_response_date    111
appVersion                  15
laguage_code                 0
country_code                 0
dtype: int64

In [24]:
reviews.duplicated().sum()

np.int64(0)

In [25]:
reviews['review_description'].duplicated().sum()

np.int64(10)

In [26]:
dp_reviews = reviews[
    reviews["review_description"].duplicated(keep=False)
].sort_values("review_description")

dp_reviews[
    ["review_description", "rating", "user_name", "review_date"]
]

    review_description  rating            user_name       review_date
79             Awesome       5        A Google user     6/1/2019 3:13
119            Awesome       5        A Google user    6/24/2017 3:19
160            Awesome       5        A Google user    8/31/2016 6:53
15                Good       5             Jm Inoue    9/3/2023 19:26
17                Good       3  Rhum “EMjhay” Roque    8/8/2023 14:37
55                Good       4        Kabir Hossain   9/17/2020 23:58
10               Great       5         Tammie Price   12/16/2023 7:35
33               Great       5  Denise Ralls-Gaines   12/19/2022 0:59
45               Great       5       Willie bennett   2/18/2022 20:49
69          Great app!       5        A Google user     1/4/2020 7:34
105         Great app!       5        A Google user  10/21/2017 18:30
143            Love it       5        A Google user  10/11/2016 20:26
159            Love it       5        A Google user    9/1/2016 20:45
74                good       5        A Google user   11/16/2019 6:29
81                good       4        A Google user   3/25/2019 17:41
132               good       5        A Google user   1/11/2017 21:55

In [28]:
reviews.shape

(161, 12)

In [ ]:
main = pd.read_csv